[package]
name = "registry-types"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.2.1", features = ["derive"] }
serde = { version = "1.0.193" }

near-primitives = { version = "0.17.0", optional = true}
near-sdk = { version = "5.0.0-alpha.1", optional = true }
