version: "3.9"  # optional since v1.27.0
services:

  actions_queryapi_coordinator:
    build:
      context: ./indexer/queryapi_coordinator
      args:
        - chain_id=mainnet
    env_file: ./indexer/queryapi_coordinator/.env
    links:
      - redis
    environment:
      - REDIS_CONNECTION_STRING=redis://redis
    command:
      - mainnet
      - from-interruption

  redis:
    image: redis
    command:
      - redis-server
      - "--save 60 1"
      - "--loglevel warning"
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      
volumes:
  db_data:
