#org: pagoda
#app: queryapi
service: queryapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 15
  environment:
    REGION: ${self:provider.region}
    HASURA_ENDPOINT: ${env:HASURA_ENDPOINT}
    HASURA_ADMIN_SECRET: ${env:HASURA_ADMIN_SECRET}
  tracing:
    lambda: true #enable X-Ray tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
      Resource: "*"
#  cfnRole: arn:aws:iam::754641474505:role/queryapi-cloudformation

# See https://github.com/getlift/lift/blob/master/docs/queue.md for configuration of SQS constructs
constructs:
  indexer-runner:
    type: queue
    fifo: true
    worker:
      handler: handler.consumer
      timeout: 15 # 1.5 minutes as lift multiplies this value by 6 (https://github.com/getlift/lift/blob/master/docs/queue.md#retry-delay)
  startFromBlock-runner:
    type: queue
    fifo: true
    #    batchSize: 100
    worker:
      handler: handler.consumer
      timeout: 15 # 1.5 minutes as lift multiplies this value by 6 (https://github.com/getlift/lift/blob/master/docs/queue.md#retry-delay)

functions:

plugins:
  - serverless-lift
#  - serverless-offline
