#org: pagoda
#app: queryapi
service: queryapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 60
#  cfnRole: arn:aws:iam::754641474505:role/queryapi-cloudformation

constructs:
  indexer-runner:
    type: queue
    worker:
      handler: handler.consumer
  startFromBlock-runner:
    type: queue
    worker:
      handler: handler.consumer

functions:

plugins:
  - serverless-lift
#  - serverless-offline
