[package]
name = "storage"
version = "0.1.0"
edition = "2021"
authors = ["Near Inc <hello@nearprotocol.com>"]

[dependencies]
anyhow = "1.0.57"
redis = { version = "0.21.5", features = ["tokio-comp", "connection-manager"] }
tracing = "0.1.34"
