[package]
name = "block-streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
aws-sdk-s3 = "0.23.0"
aws-config = "0.53.0"
borsh = "0.10.2"
chrono = "0.4.25"
futures = "0.3.5"
redis = { version = "0.21.5", features = ["tokio-comp", "connection-manager"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
tracing = "0.1.34"
tokio = { version = "1.1", features = ["sync", "time", "macros", "rt-multi-thread"] }
tokio-util = "0.6.7"
wildmatch = "2.1.1"

near-lake-framework = "0.7.1"
near-jsonrpc-client = "0.5.1"
near-jsonrpc-primitives = "0.16.0"
