[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
tokio = "1.28"
serde_json = "1.0.108"

near-jsonrpc-client = "0.6.0"
near-primitives = "0.17.0"
near-jsonrpc-primitives = "0.17.0"
