[package]
name = "indexer_rules_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
