name: Block Streamer

on:
  push:
    branches: [ main ]
    paths:
      - "block-streamer/**"
  pull_request:
    paths:
      - "block-streamer/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check
      working-directory: ./block-streamer
      run: cargo check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      working-directory: ./block-streamer
      run: cargo test


  format:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.70.0
        override: true
        profile: minimal
        components: rustfmt
    - name: Check formatting
      working-directory: ./block-streamer
      run: |
        cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.70.0
        override: true
        profile: minimal
        components: clippy
    - name: Clippy check
      working-directory: ./block-streamer
      run: |
        cargo clippy
