name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, staging, production ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.68.0
        override: true
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: |
        cargo fmt -- --check

  rustclippy:
    name: rustclippy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.68.0
        override: true
        profile: minimal
        components: clippy
    - name: Clippy check
      run: |
        cargo clippy
