name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "indexer/**"
  pull_request:
    branches: [ main, stable ]
    paths:
      - "indexer/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: Move this to New Coordinator's CI Workflow
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Run check
      working-directory: ./indexer
      run: cargo check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: Move this to New Coordinator's CI Workflow
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Run check
      working-directory: ./indexer
      run: cargo test


  rustfmt:
    name: rustfmt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.68.0
        override: true
        profile: minimal
        components: rustfmt
    # TODO: Move this to New Coordinator's CI Workflow
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Check formatting
      working-directory: ./indexer
      run: |
        cargo fmt -- --check

  rustclippy:
    name: rustclippy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.68.0
        override: true
        profile: minimal
        components: clippy
    # TODO: Move this to New Coordinator's CI Workflow
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Clippy check
      working-directory: ./indexer
      run: |
        cargo clippy
