name: Deploy Lambdas

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: Path to Serverless Lambda directory
      environment:
        required: true
        type: string
        description: Github environment to deploy to

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node Dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Serverless Deploy
        run: ./node_modules/.bin/sls deploy --stage ${{ vars.SERVERLESS_STAGE_NAME }}
        working-directory: ${{ inputs.working-directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HASURA_ENDPOINT: ${{ vars.HASURA_ENDPOINT }}
          HASURA_ENDPOINT_V2: ${{ vars.HASURA_ENDPOINT_V2 }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          PG_ADMIN_USER: ${{ secrets.PG_ADMIN_USER }}
          PG_ADMIN_PASSWORD: ${{ secrets.PG_ADMIN_PASSWORD }}
          PG_ADMIN_DATABASE: ${{ secrets.PG_ADMIN_DATABASE }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
