name: Deploy Lambdas

on:
  pull_request:
    branches: [ main, stable ]
    paths:
      - "indexer-js-queue-handler/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node Dependencies
        run: npm install
        working-directory: ./indexer-js-queue-handler

      - name: Run tests
        run: npm test
        working-directory: ./indexer-js-queue-handler

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node Dependencies
        run: npm install
        working-directory: ./indexer-js-queue-handler

      - name: Serverless Deploy
        run: ./node_modules/.bin/sls deploy --stage ${{ github.ref == 'refs/heads/stable' && 'prod' || 'dev' }}
        working-directory: ./indexer-js-queue-handler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
