name: Deploy Dev Lambdas

on:
  push:
    branches: [main]
    paths:
      - "indexer-js-queue-handler/**"

jobs:
  test:
    uses: ./.github/workflows/test-lambdas.yml
    with:
      working-directory: ./indexer-js-queue-handler

  deploy:
    uses: ./.github/workflows/deploy-lambdas.yml
    needs: test
    secrets: inherit
    with:
      working-directory: ./indexer-js-queue-handler
      environment: LAMBDA_DEV
