name: Test Lambdas

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: Path to Serverless Lambda directory

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node Dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}
